import { CvgStore } from '/tmp/cvg-delivery-audit-20260913-bcsdpob2/repo/packages/domain/src/index.ts';
import { createDurableDeepSeekAcpGovernance } from '/tmp/cvg-delivery-audit-20260913-bcsdpob2/repo/packages/harness-adapters/src/index.ts';
const store = new CvgStore({bootstrapPassword:'synthetic-password-123'});
function ctx(prefix) { const user=[...store.users.values()].find(u=>u.login.startsWith(prefix)); const opt=store.contextOptions(user.id)[0]; const s=store.createSession(user.id,'synthetic-'+prefix,'csrf-'+prefix,60);return store.resolveContext(user.id,{unitId:opt.unit.id,workspaceId:opt.workspace.id},'test','independent-probe',null,null,s.id); }
const vet=ctx('ana.'); const stock=ctx('admin');
const patient=store.listPatients(vet)[0]; const encounter=store.createEncounter(vet,{patientId:patient.id,appointmentId:null,chiefComplaint:'synthetic probe',urgency:'ROUTINE'});
const lot=[...store.lots.values()].find(l=>l.quantity>0&&Date.parse(l.expiresOn)>Date.now()&&store.stockLocations.get(l.locationId)?.unitId===vet.unitId);
console.log('fixture', {encounter:!!encounter,lot:!!lot});
if(encounter&&lot){ const order=store.createMedicationOrder(vet,{patientId:encounter.patientId,encounterId:encounter.id,productId:lot.productId,dose:'1',route:'oral',frequency:'daily'}); store.updateMedicationOrderStatus(vet,order.id,'COMPLETED'); try {const d=store.dispenseMedication(stock,order.id,lot.id,1);console.log('dispenseCompleted',{status:store.medicationOrders.get(order.id)?.status,quantity:d.quantity,stockReduced:store.lots.get(lot.id)?.quantity===lot.quantity-1});}catch(e){console.log('dispenseCompletedError',e.code,e.message)} const suspended=store.updateMedicationOrderStatus(vet,order.id,'SUSPENDED');const reopened=store.updateMedicationOrderStatus(vet,order.id,'ACTIVE');console.log('reopenCompleted',{intermediate:suspended.status,final:reopened.status}); }
const governance=createDurableDeepSeekAcpGovernance({store}); const session=await governance.createSession(vet,{purpose:'OPERATIONS',patientId:null,encounterId:null},{engineCommit:'synthetic-commit',profileDigest:'synthetic-profile'});
const input={sessionId:session.id,prompt:'synthetic request',purpose:'OPERATIONS',patientId:null,encounterId:null,requestedTool:null,approvalId:null,idempotencyKey:'probe-1'};
const auth=await governance.authorizeTurn(vet,session,input,null); console.log('acpWithoutBudget',{disposition:auth.disposition,reservations:store.budgetReservations.size});
const r=store.reserveBudget(vet,{sessionId:session.id,category:'TOKENS',units:100,cap:1000,ttlMs:60000});const settled=store.settleBudgetReservation(r.id,900);const next=store.reserveBudget(vet,{sessionId:session.id,category:'TOKENS',units:900,cap:1000,ttlMs:60000}); console.log('budgetOverage',{actual:900,recorded:settled.reservation.consumedUnits,overage:settled.overageUnits,nextReserved:next.reservedUnits,nextStatus:next.status});
const calls=[];const budget={reserve:units=>{const id='res-'+calls.length;calls.push(['reserve',id,units]);return id},settle:(id,units)=>{calls.push(['settle',id,units])},release:id=>calls.push(['release',id])};const g1=createDurableDeepSeekAcpGovernance({store,budget});await g1.authorizeTurn(vet,session,{...input,idempotencyKey:'restart'},null);const g2=createDurableDeepSeekAcpGovernance({store,budget});const result=await g2.recordTurn(vet,session,{...input,idempotencyKey:'restart'},{status:'COMPLETED',response:'done',model:'synthetic',inputTokens:4,outputTokens:2,correlationId:vet.correlationId});console.log('acpRestartSettlement',{calls,usageStatus:result.turn.usage.status,reservationId:result.turn.usage.reservationId});
await governance.authorizeTurn(vet,session,{...input,idempotencyKey:'revoked-in-flight'},null);store.revokeAllSessions(vet.actorId);let rejected=false;try{store.validateContext(vet)}catch{rejected=true}const revokedResult=await governance.recordTurn(vet,session,{...input,idempotencyKey:'revoked-in-flight'},{status:'COMPLETED',response:'sensitive result',model:'synthetic',inputTokens:1,outputTokens:1,correlationId:vet.correlationId});console.log('recordAfterRevocation',{contextRejected:rejected,turnStatus:revokedResult.turn.status,persisted:store.aiTurns.has(revokedResult.turn.id)});
