import { CvgStore } from '/tmp/cvg-aaa2-continuation-audit-egq6c0o7/repo/packages/domain/src/index.ts';
import { createDurableDeepSeekAcpGovernance } from '/tmp/cvg-aaa2-continuation-audit-egq6c0o7/repo/packages/harness-adapters/src/index.ts';
const store = new CvgStore({bootstrapPassword:'synthetic-password-123'});
function ctx(prefix) { const user=[...store.users.values()].find(u=>u.login.startsWith(prefix)); const opt=store.contextOptions(user.id)[0]; const s=store.createSession(user.id,'synthetic-'+prefix,'csrf-'+prefix,60);return store.resolveContext(user.id,{unitId:opt.unit.id,workspaceId:opt.workspace.id},'test','independent-probe',null,null,s.id); }
const vet=ctx('ana.'); const stock=ctx('admin');
const governance=createDurableDeepSeekAcpGovernance({store}); const session=await governance.createSession(vet,{purpose:'OPERATIONS',patientId:null,encounterId:null},{engineCommit:'synthetic-commit',profileDigest:'synthetic-profile'});
const input={sessionId:session.id,prompt:'synthetic request',purpose:'OPERATIONS',patientId:null,encounterId:null,requestedTool:null,approvalId:null,idempotencyKey:'probe-1'};
const auth=await governance.authorizeTurn(vet,session,input,null); console.log('acpWithoutBudget',{disposition:auth.disposition,reservations:store.budgetReservations.size});
const r=store.reserveBudget(vet,{sessionId:session.id,category:'TOKENS',units:100,cap:1000,ttlMs:60000});const settled=store.settleBudgetReservation(r.id,900);const next=store.reserveBudget(vet,{sessionId:session.id,category:'TOKENS',units:900,cap:1000,ttlMs:60000}); console.log('budgetOverage',{actual:900,recorded:settled.reservation.consumedUnits,overage:settled.overageUnits,nextReserved:next.reservedUnits,nextStatus:next.status});
const calls=[];const budget={reserve:units=>{const id='res-'+calls.length;calls.push(['reserve',id,units]);return id},settle:(id,units)=>{calls.push(['settle',id,units])},release:id=>calls.push(['release',id])};const g1=createDurableDeepSeekAcpGovernance({store,budget});await g1.authorizeTurn(vet,session,{...input,idempotencyKey:'restart'},null);const g2=createDurableDeepSeekAcpGovernance({store,budget});const result=await g2.recordTurn(vet,session,{...input,idempotencyKey:'restart'},{status:'COMPLETED',response:'done',model:'synthetic',inputTokens:4,outputTokens:2,correlationId:vet.correlationId});console.log('acpRestartSettlement',{calls,usageStatus:result.turn.usage.status,reservationId:result.turn.usage.reservationId});
await governance.authorizeTurn(vet,session,{...input,idempotencyKey:'revoked-in-flight'},null);store.revokeAllSessions(vet.actorId);let rejected=false;try{store.validateContext(vet)}catch{rejected=true}const revokedResult=await governance.recordTurn(vet,session,{...input,idempotencyKey:'revoked-in-flight'},{status:'COMPLETED',response:'sensitive result',model:'synthetic',inputTokens:1,outputTokens:1,correlationId:vet.correlationId});console.log('recordAfterRevocation',{contextRejected:rejected,turnStatus:revokedResult.turn.status,persisted:store.aiTurns.has(revokedResult.turn.id)});
