apiVersion: 1
datasources:
  - name: CVG Prometheus
    uid: cvg-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: CVG Tempo
    uid: cvg-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
